'use strict';Object.defineProperty(exports, "__esModule", { value: true });exports.
















getCalendarMonth = getCalendarMonth;exports.











getNestedCalendarMonth = getNestedCalendarMonth;exports.




















monthNameFinder = monthNameFinder;var _week = require('./week');var _calendar = require('../config/calendar.config');var _name = require('./name.finder');var _name2 = _interopRequireDefault(_name);function _interopRequireDefault(obj) {return obj && obj.__esModule ? obj : { default: obj };}var MONTH_NAMES = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']; /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @description CONSTRUCTOR: Convenience method. Returns a set of weeks for a predefined month range. Specifically,
                                                                                                                                                                                                                                                                                                                                                                                                                                                 * this returns a calendar month - i.e., 5 weeks/35 days. A calendar month includes days preceding and following
                                                                                                                                                                                                                                                                                                                                                                                                                                                 * the actual days of the month.
                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @export
                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {any} {date, getEvents, formatDate, isNested} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @returns {Array<Day>} An Array of Days
                                                                                                                                                                                                                                                                                                                                                                                                                                                 */function getCalendarMonth(_ref) {var date = _ref.date,getEvents = _ref.getEvents,formatDate = _ref.formatDate;return (0, _week.getNWeeks)({ date: date, getEvents: getEvents, formatDate: formatDate, numOfWeeks: (0, _calendar.WEEKS_IN_MONTH)() });} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * @description Returns a nested array of Days. Each set of days is grouped in a week-long array.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * @export
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * @param {any} {date, getEvents, formatDate} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           * @returns 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           */function getNestedCalendarMonth(_ref2) {var date = _ref2.date,getEvents = _ref2.getEvents,formatDate = _ref2.formatDate;var weeks = [];var _date = date;var weeksInMonth = (0, _calendar.WEEKS_IN_MONTH)();for (var week = 0; week < weeksInMonth; week++) {weeks.push((0, _week.getNWeeks)({ date: _date, getEvents: getEvents, formatDate: formatDate, numOfWeeks: 0 }));_date = (0, _week.getDateInFollowingWeek)(_date);}return weeks;} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @description Returns a month name, when given a month number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @export
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @param {any} [monthNames=MONTH_NAMES] 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          * @returns {string} A month name
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          */function monthNameFinder() {var monthNames = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : MONTH_NAMES;return (0, _name2.default)(monthNames);}