'use strict';Object.defineProperty(exports, "__esModule", { value: true });exports.





















getWeekForDate = getWeekForDate;exports.












getDateInFollowingWeek = getDateInFollowingWeek;exports.










getNWeeks = getNWeeks;exports.

















weekDayNameFinder = weekDayNameFinder;var _start_of_week = require('./date-utils/start_of_week');var _start_of_week2 = _interopRequireDefault(_start_of_week);var _end_of_week = require('./date-utils/end_of_week');var _end_of_week2 = _interopRequireDefault(_end_of_week);var _get_range_of_dates = require('./date-utils/get_range_of_dates');var _get_range_of_dates2 = _interopRequireDefault(_get_range_of_dates);var _add_days = require('./date-utils/add_days');var _add_days2 = _interopRequireDefault(_add_days);var _day = require('./day');var _day2 = _interopRequireDefault(_day);var _name = require('./name.finder');var _name2 = _interopRequireDefault(_name);function _interopRequireDefault(obj) {return obj && obj.__esModule ? obj : { default: obj };}var WEEK_DAY_NAMES = { 0: 'Sunday', 1: 'Monday', 2: 'Tuesday', 3: 'Wednesday', 4: 'Thursday', 5: 'Friday', 6: 'Saturday' }; /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * @desc Creates an array of dates that corresponds to a week range
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * @param {any} date 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * @returns {Array<Day>} Dates
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */function getWeekForDate(_ref) {var date = _ref.date,getEvents = _ref.getEvents,formatDate = _ref.formatDate;return (0, _get_range_of_dates2.default)((0, _start_of_week2.default)(date), (0, _end_of_week2.default)(date)).map(function (date) {return (0, _day2.default)({ date: date, getEvents: getEvents, formatDate: formatDate });});} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             *  Returns the date one week later when given a date 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * @export
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * @param {any} date 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * @param {any} [daysInWeek=DAYS_IN_WEEK()] 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             * @returns {Date}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             */function getDateInFollowingWeek(date) {var daysInWeek = arguments.length > 1 && arguments[1] !== undefined ? arguments[1] : 7;return (0, _add_days2.default)(date, daysInWeek);} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @description Returns a set of _n_ weeks, when given a start seed.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @export
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {any} {date, getEvents, formatDate, numOfWeeks} 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @returns {Array<Date>}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */function getNWeeks(_ref2) {var date = _ref2.date,getEvents = _ref2.getEvents,formatDate = _ref2.formatDate,numOfWeeks = _ref2.numOfWeeks;if (!date) {return [];}var week = getWeekForDate({ date: date, getEvents: getEvents, formatDate: formatDate });return !numOfWeeks ? week : week.concat(getNWeeks({ date: getDateInFollowingWeek(date), getEvents: getEvents, formatDate: formatDate, numOfWeeks: --numOfWeeks }));} /**
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @description CONSTRUCTOR: Creates a function that returns Week DAy names.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @export
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @param {any} [weekDays={}] 
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 * @returns {Function} A function that returns a Week Day name when given a Week Day number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 */function weekDayNameFinder() {var weekDayNames = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : WEEK_DAY_NAMES;return (0, _name2.default)(weekDayNames);}